name: vigenesia_app
description: "Aplikasi Visi Generasi Indonesia (ViGeneSia) merupakan aplikasi untuk tugas mata kuliah Teknologi Web Service dari Universitas Bina Sarana Informatika."
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  hooks_riverpod:
  cupertino_icons: ^1.0.6
  http: ^0.13.4
  loader_overlay: ^4.0.3
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  path_provider: ^2.0.10
  flutter_hooks: ^0.20.5
  intl: ^0.19.0
  flutter_riverpod: ^2.6.1
  flutter_speed_dial: ^7.0.0
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons:

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/img/